---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/data/header.md
  label: Header Config
- type: document
  path: content/data/footer.json
  label: Footer Config
- type: directory
  path: content/services
  label: Leistungen
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - service-template
- type: document
  path: content/data/home.md
  label: Home Config
- type: document
  path: content/data/projects.md
  label: Projekte Config
- type: document
  path: content/data/about.md
  label: About Config
- type: document
  path: content/data/impressum.md
  label: Impressum Config
- type: document
  path: content/data/datenschutz.md
  label: Datenschutz Config
- type: document
  path: content/data/info.json
  label: Info Page
- type: heading
  label: General Config
- type: document
  path: config.json
  label: Site Info
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run forestry:preview
